version: 0.0
os: linux

files:
  - source: /
    # EC2에 저장할 경로
    destination: /home/ubuntu/sweatier-server

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu
